### ISSUE TITLE
Q: Registering multiple service instances?

### ISSUE THREAD

**Issue by mmisztal1980** [cecilphillip/aspnet-servicediscovery-patterns#1]
Hi there,

I've got a question on how should I proceed if I'd like to register multiple instances of service X ?
In [this](https://github.com/cecilphillip/aspnet-servicediscovery-patterns/blob/master/self_registration/src/SchoolAPI/Infrastructure/Extensions.cs) sample, a previous instance of the service is de-registered 1st. What's the recommended approach to registering multiple service instances?

```
var registration = new AgentServiceRegistration()
                {
                    ID = consulConfig.Value.ServiceID,
                    Name = consulConfig.Value.ServiceName,
                    Address = $"{uri.Scheme}://{uri.Host}",
                    Port = uri.Port,
                    Tags = new[] { "Students", "Courses", "School" }
                };

                var registrationTask = consulClient.Agent.ServiceDeregister(registration.ID)
                    .Then(() => consulClient.Agent.ServiceRegister(registration));

                registrationTask.Wait();
```

**Comment by cecilphillip** [comment]
Hi @mmisztal1980. Sorry I just saw this.
You probably want to give each instance a unique ID. Something like [this](https://github.com/cecilphillip/aspnet-servicediscovery-patterns/blob/master/health_checks/src/SchoolAPI/Infrastructure/Extensions.cs#L33) or you could use a GUID instead.

Then you could spin up multiple processes, multiple docker containers... whatever your mechanism is. Each would have the same "Name" and different "ID".

Hope that helps.

**Comment by mmisztal1980** [comment]
Awesome, thank you :)
